# Generated by Django 4.1.7 on 2023-02-23 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_alter_reservation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='nombre_de_place',
            new_name='nombre_de_place_restant',
        ),
    ]
