# Generated by Django 4.1.7 on 2023-02-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_rename_nombre_de_place_place_nombre_de_place_restant'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='disponibilite',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='nombre_de_place_restant',
            field=models.IntegerField(default=2),
        ),
    ]
