# Generated by Django 4.1.7 on 2023-03-13 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_reserve_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='telephone',
        ),
    ]
