# Generated by Django 4.1.7 on 2023-03-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_client_email_client_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='motDePass',
            field=models.CharField(default='1234', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='nomUtisateur',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
