# Generated by Django 4.1.2 on 2023-04-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_client_motdepass_client_nomutisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEtDeExpediteur', models.CharField(max_length=50)),
                ('nomDuDestinatair', models.CharField(max_length=100)),
                ('objetAEnvoyer', models.CharField(max_length=50)),
                ('prixDeLobjet', models.IntegerField()),
                ('telephone', models.CharField(max_length=50)),
                ('Cnib', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='reserve',
            name='NomEtPrenom',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
