# Generated by Django 4.1.7 on 2023-04-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0012_rename_cnib_courier_cnib_courier_validerarrive_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='reservation',
            name='NomEtPrenom',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
